services:
  db:
    image: mariadb:12.3
    container_name: mariadb_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mariadb_db:/var/lib/mysql

  server:
    build: .
    container_name: projeto-prog4
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
    ports:
      - '${PORT}:3000'
    depends_on:
      - db

volumes:
  mariadb_db:
